from __future__ import annotations
"""
Nimbus Guard; reporting utilities

"""
from typing import Any, Dict, List
import datetime as _dt
from collections import Counter

from jinja2 import Environment, DictLoader, StrictUndefined
import markdown as _md

#------------- Severity ranking  ---------------------------------------------------------------------------------

SEVERITY_ORDER: List[str] = ["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"]

#------------- Jinja2 in-memory templates ---------------------------------------------------------------------------------

_TEMPLATES: Dict[str, str] = {
    "markdown": r"""
# Nimbus Guard Report

**Run Timestamp (UTC):** {{ timestamp }}  
**Total Findings:** {{ totals.total }}  
**Fail Threshold:** {{ fail_on }}

## Findings by Severity
| Severity | Count |
|---:|---:|
{% for sev in ["CRITICAL","HIGH","MEDIUM","LOW","INFO"] -%}
| {{ sev }} | {{ totals.by_severity.get(sev, 0) }} |
{% endfor %}

## Findings by Service
| Service | Count |
|---:|---:|
{% for svc, cnt in totals.by_service|dictsort -%}
| {{ svc }} | {{ cnt }} |
{% endfor %}

## Details
{% if findings %}
| Severity | Service | Region | Resource | Title |
|---|---|---|---|---|
{% for f in findings -%}
| {{ f.severity }} | {{ f.service }} | {{ f.region or "global" }} | {{ f.resource_id }} | {{ f.title }} |
{% endfor %}

### Finding Details
{% for f in findings -%}
#### {{ loop.index }}. {{ f.severity }} — {{ f.service }} — {{ f.resource_id }}
- **Region:** {{ f.region or "global" }}
- **Title:** {{ f.title }}
- **Severity:** {{ f.severity }}
- **Service:** {{ f.service }}
- **Details (YAML-like):**

{{ f.details | to_nice_yaml }}

{% endfor %}
{% else %}
_No findings were produced by the checks._
{% endif %}

*Generated by Nimbus Guard. Report is self-contained and link-free.*
""".strip()
}

def _build_env() -> Environment:
    """
    Create a Jinja2 environment configured for in-memory templates,
    consistent whitespace handling, and strict undefined variables.
    """
    return Environment(
        loader=DictLoader(_TEMPLATES),
        undefined=StrictUndefined,
        autoescape=False,   # Markdown/plaintext output (HTML is post-processed)
        trim_blocks=True,
        lstrip_blocks=True,
    )

_env: Environment = _build_env()

def _to_nice_yaml(data: Any) -> str:
    """
    Render dicts/lists in a stable, human-readable way without introducing
    YAML anchors/aliases. If PyYAML isn't available, fall back to repr().
    """
    try:
        import yaml  # type: ignore
        return yaml.safe_dump(data, sort_keys=True, default_flow_style=False).rstrip()
    except Exception:
        # Fallback keeps the report functional even if PyYAML is missing.
        return repr(data)

# register as a Jinja filter
_env.filters["to_nice_yaml"] = _to_nice_yaml

#------------- Normalisation & summaries ---------------------------------------------------------------------------------

def _normalize_findings(findings: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Ensure each finding has the expected keys/types and a consistent shape,
    then sort by severity (desc), service, resource_id—matching original behavior.
    """
    norm: List[Dict[str, Any]] = []
    for f in findings or []:
        norm.append(
            {
                "service": (f.get("service") or "unknown"),
                "resource_id": (f.get("resource_id") or "unknown"),
                "title": (f.get("title") or "Untitled"),
                "severity": (str(f.get("severity") or "LOW")).upper(),
                "region": f.get("region"),
                "details": f.get("details") or {},
            }
        )

    sev_index: Dict[str, int] = {s: i for i, s in enumerate(SEVERITY_ORDER)}

    # Sort by severity DESC (using index), then service, then resource id
    # Unknown severities sort with index 0 (INFO) to avoid over-elevating them.
    norm.sort(
        key=lambda x: (sev_index.get(x["severity"], 0), x["service"], x["resource_id"]),
        reverse=True,
    )
    return norm

def _totals(findings: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Compute high-level totals used by templates.
    """
    by_sev = Counter([f["severity"] for f in findings])
    by_svc = Counter([f["service"] for f in findings])
    return {
        "total": len(findings),
        "by_severity": dict(by_sev),
        "by_service": dict(by_svc),
    }

#------------- Public API ----------------------------------------------------------------------------------------

def render_markdown(findings: List[Dict[str, Any]], fail_on: str = "HIGH") -> str:
    """
    Render a Markdown report from findings through the in-memory Jinja2 template.

    Args:
        findings: List of finding dicts (already JSON-serializable).
        fail_on:  Threshold that CI may use to determine failure; displayed only.

    Returns:
        Markdown text as a single string.
    """
    f = _normalize_findings(findings)
    tpl = _env.get_template("markdown")
    md = tpl.render(
        timestamp=_dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        totals=_totals(f),
        findings=f,
        fail_on=fail_on,
    )
    return md

def render_html(findings: List[Dict[str, Any]], fail_on: str = "HIGH") -> str:
    """
    Convert the Markdown report into a self-contained HTML document with
    small, deterministic CSS. No network requests or external assets.
    """
    md_text = render_markdown(findings, fail_on=fail_on)

    # Convert the Markdown to HTML using python-markdown with lightweight extensions.
    body = _md.markdown(
        md_text,
        extensions=["extra", "tables", "sane_lists", "toc"],
        output_format="html5",
    )

    # Minimal embedded CSS for readability.
    css = (
        "body { font-family: system-ui, Segoe UI, Roboto, Helvetica, Arial, sans-serif; "
        "line-height: 1.5; padding: 24px; }"
        "h1, h2, h3, h4 { margin-top: 1.25em; }"
        "table { border-collapse: collapse; width: 100%; margin: 12px 0; }"
        "th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }"
        "th { background: #f5f5f5; }"
        "code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }"
        "pre { background: #fafafa; border: 1px solid #eee; padding: 12px; overflow: auto; }"
    )

    html = (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "<title>Nimbus Guard Report</title>\n"
        f"<style>{css}</style>\n"
        "<body>\n"
        f"{body}\n"
        "</body>\n"
        "</html>"
    )
    return html
